version: '3'

services:
  product-service:
    container_name: product-service
    image: 'product-service'
    build:
      context: product-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - product-db
  product-db:
    image: 'postgres:11-alpine'
    container_name: product-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product_db
    volumes:
      - product-db:/var/lib/postgresql/data
volumes:
  product-db: