apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: car-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: car-app
  template:
    metadata:
      name: car-app
      labels:
        name: car-app
    spec:
      containers:
        - name: car-app
          image: shabir67/car-app-v1:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongo"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_USERNAME
              value: "rootuser"
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: "rootpass"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "carmanagement"
---

apiVersion: v1
kind: Service
metadata:
  name: car-app-service
spec:
  selector:
    name: car-app
  ports:
    - port: 80
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: car-ingress
  labels:
    name: car-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: "car.local"
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: car-app-service
                port:
                  number: 80
